[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "schwurve"
authors = [{name = "Ayjent", email = "rogue.cherry.us@gmail"}]
dynamic = ["version", "description"]
